title: My test project
hero_image: images/banner.png
description: First practice project 
version: 4
listed: false
copyedit: false
last_tested: "2020-10-20"
steps:
  - title: Introduction
  - title: Step 1
  - title: Step 2
  - title: Step 3
  - title: What next?
